### PR TITLE
add actions

### PR DESCRIPTION
**Pull request by TylerLeonhardt**

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
@devblackops I never received a comment from the PSSA GitHub action. Any help here?

**Comment by devblackops** [comment]
> @devblackops I never received a comment from the PSSA GitHub action. Any help here?

I haven't tested since they refactored the Actions but it's on my TODO!

I'm pretty sure I need to add some metadata file to describe the inputs/outputs of the action.

**Comment by devblackops** [comment]
It definitely needs your GH token so it can post back to the PR

**Comment by devblackops** [comment]
@TylerLeonhardt The action won't add a comment unless there are errors (by default). Have your module fail some checks and see what happens.

```
PSScriptAnalyzer results:
Errors:      0
Warnings:    0
Information: 0
```

**Pull request merged**
